import type { Metadata } from "next";
import { Cabin, DM_Sans, Oxanium } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const mainFont = Cabin({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Leonard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Toaster position="top-right" reverseOrder={false} />
        <div className="mx-auto max-w-screen-2xl">{children}</div>
      </body>
    </html>
  );
}
